---
name: ci
on: [push, pull_request]
jobs:
  build_extension:
    name: "Build extension"
    runs-on: ubuntu-latest
    container:
      image: "node:lts"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: 'npm install'
      - name: Compile
        run: 'npm run compile'
      - name: Lint
        run: 'npm run lint'
      - name: Build extension
        run: 'npm run build'

